### ISSUE TITLE
Repo does not work with react-scripts >= 4.0.0

### ISSUE THREAD

**Issue by adamduren** [wallabyjs/wallaby-create-react-app-ts#28]
I first discovered this when trying to setup wallaby on my personal project and after research discovered this repo with a recommended `wallaby.js` config. I tried cloning and upgrading this repo and experienced that same result.

VSCode Wallaby.js Tests Output
```
‌0 failing tests, 0 passing (only executed src/apis/user.test.ts)  ​Launch Coverage & Test Explorer​ | ​Search Tests​

ReferenceError: jasmine is not defined 
    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:1299:24) 
    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:898:12) 
    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:746:10) 
    at jestAdapter (./node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:93:15) 
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    at runTestInternal (./node_modules/jest-runner/build/runTest.js:380:16) 
    at runTest (./node_modules/jest-runner/build/runTest.js:472:34) 
```

**Comment by ArtemGovorov** [comment]
With your version of CRA, you don't need any Wallaby config, it should start with [auto-config](https://wallabyjs.com/docs/integration/jest.html#starting-wallaby-on-a-project-with-configured-jest) for you in your project.
