### ISSUE TITLE
Postprocessor run failure error using this configuration

### ISSUE THREAD

**Issue by alecmce** [wallabyjs/wallaby-create-react-app-ts#3]
I have an (almost) vanilla create-react-app repo --typescript generated app and was using this configuration to get wallaby running over its tests. I got this error:

```
[Error] Postprocessor run failure: Failed to run preprocessors on src/App.js, Error: [BABEL] /repo/src/App.js: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined. (While processing: "/repo/node_modules/babel-preset-react-app/index.js") 
[Error]     at module.exports (/repo/node_modules/babel-preset-react-app/create.js:58:11) 
[Error]     at module.exports (/repo/node_modules/babel-preset-react-app/index.js:19:10) 
[Error]     at loadDescriptor (/repo/node_modules/@babel/core/lib/config/full.js:165:14) 
[Error]     at cachedFunction (/repo/node_modules/@babel/core/lib/config/caching.js:33:19) 
[Error]     at loadPresetDescriptor (/repo/node_modules/@babel/core/lib/config/full.js:235:63) 
[Error]     at config.presets.reduce (/repo/node_modules/@babel/core/lib/config/full.js:77:21) 
[Error]     at Array.reduce (<anonymous>) 
[Error]     at recurseDescriptors (/repo/node_modules/@babel/core/lib/config/full.js:74:38) 
[Error]     at loadFullConfig (/repo/node_modules/@babel/core/lib/config/full.js:108:6) 
[Error]     at transformSync (/repo/node_modules/@babel/core/lib/transform.js:41:38) 
[Error]     at Object.transform (/repo/node_modules/@babel/core/lib/transform.js:22:38) 
[Error]     at **/*.js?(x) (/repo/wallaby.js:24:32) 
[Error]     at process._tickCallback (internal/process/next_tick.js:61:11) 
```

Following [this issue](https://github.com/wallabyjs/public/issues/285) I was able to fix with the inclusion of the line

```process.env.BABEL_ENV = 'test'```

in my wallaby config.

**Comment by ArtemGovorov** [comment]
I'm a bit confused - the suggested code statement is already [present in the repo's config](https://github.com/wallabyjs/wallaby-create-react-app-ts/blob/master/wallaby.js#L3). Looks like your commit is just duplicating the line above -https://github.com/alecmce/wallaby-create-react-app-ts/commit/9d2d6c63c6a16a500c82ce12a76407e73d63b803#diff-4e87b2c6dcfa10beeaf6797eaa6c66ecL3?

**Comment by alecmce** [comment]
Uhh ... I'm a bit confused too. I have no earthly idea how I 1. didn't copy that line into my config and 2. didn't read it when I went to make that change. I'll go crawl under a rock :/
